# 项目服务配置
service:
  name: "pyrethrum"
  listen: ":8082"
  pre: "api/v1"
  version: "v1.0"

# mysql配置
mysql:
  # 最大打开连接
  maxOpenConns: 20
  # 设置空闲连接
  maxIdleConns: 20
  # DSN
  dsn: "root:123456@tcp(192.168.0.103:13306)/satellite?parseTime=true&charset=utf8&loc=Local"

# redis配置
redis:
  addr: "192.168.0.103:16379"
  password: "123456"
  db: 0

# etcd配置
etcd:
  addr: "192.168.0.103:2379"
  deadline: 5

# ipfs配置
ipfs:
  addr: "192.168.0.103:5001"
